---

#- apt_repository:
#    name: ppa:longsleep/golang-backports
#    state: present 

#- apt_repository:
#    name: deb http://ppa.launchpad.net/neovim-ppa/unstable/ubuntu xenial main
#    state: present

- name: Install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - python
    - acl
    - dnsmasq-base 
    - git 
    - liblxc1 
    - lxc-dev 
    - libacl1-dev 
    - make 
    - pkg-config 
    - rsync 
    - squashfs-tools 
    - tar 
    - xz-utils
    - build-essential
    - jq
    - vim
    - bash-completion
    - rxvt-unicode-256color
    - strace
    - openvpn
    - golang
    - unhide
