---

- name: Install packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - acl
    - dnsmasq-base 
    - git 
    - golang 
    - liblxc1 
    - lxc-dev 
    - libacl1-dev 
    - make 
    - pkg-config 
    - rsync 
    - squashfs-tools 
    - tar 
    - xz-utils
    - build-essential
    - virtualbox
